# Use the official PHP CLI base image
FROM php:8.2-cli

# Set the working directory inside the container
WORKDIR /usr/src/app

# CMD specifies the default command to run in the container
CMD ["php"]

# FROM php:8.2-cli

# # Set the working directory inside the container
# WORKDIR /usr/src/code

# # Copy the PHP source file into the container
# COPY temp.php .

# # Set the default command to execute the PHP file
# ENTRYPOINT ["php", "temp.php"]
